const cities = [
    // {"id": 0, "name": "All Cities"},
    {"id": 1, "name": "Abbottabad"},
    {"id": 2, "name": "Abdul Hakeem"},
    {"id": 3, "name": "Ahmedpur East"},
    {"id": 4, "name": "Ahmedpur Sial"},
    {"id": 5, "name": "Aliabad"},
    {"id": 6, "name": "Alipur Chatha"},
    {"id": 7, "name": "Alpuri"},
    {"id": 8, "name": "Aminpur"},
    {"id": 9, "name": "Arifwala"},
    {"id": 10, "name": "Athara Hazari"},
    {"id": 11, "name": "Athmuqam"},
    {"id": 12, "name": "Attock"},
    {"id": 13, "name": "Awaran"},
    {"id": 14, "name": "Baddomalhi"},
    {"id": 15, "name": "Badin"},
    {"id": 16, "name": "Bagh"},
    {"id": 17, "name": "Bahawalnagar"},
    {"id": 18, "name": "Bahawalpur"},
    {"id": 19, "name": "Balianwala"},
    {"id": 20, "name": "Bannu"},
    {"id": 21, "name": "Barkhan"},
    {"id": 22, "name": "Battagram"},
    {"id": 23, "name": "Bhakkar"},
    {"id": 24, "name": "Bhalwal"},
    {"id": 25, "name": "Bhera"},
    {"id": 26, "name": "Bucheki"},
    {"id": 27, "name": "Burewala"},
    {"id": 28, "name": "Chakwal"},
    {"id": 29, "name": "Chaman"},
    {"id": 30, "name": "Changa Manga"},
    {"id": 31, "name": "Charsadda"},
    {"id": 32, "name": "Chichawatni"},
    {"id": 33, "name": "Chilas"},
    {"id": 34, "name": "Chiniot"},
    {"id": 35, "name": "Chishtian"},
    {"id": 36, "name": "Chitral"},
    {"id": 37, "name": "Chowk Azam"},
    {"id": 38, "name": "Chunian"},
    {"id": 39, "name": "Dadu"},
    {"id": 40, "name": "Dalbandin"},
    {"id": 41, "name": "Daska"},
    {"id": 42, "name": "Dasu"},
    {"id": 43, "name": "Dera Allahyar"},
    {"id": 44, "name": "Dera Ghazi Khan"},
    {"id": 45, "name": "Dera Ismail Khan"},
    {"id": 46, "name": "Dera Murad Jamali"},
    {"id": 47, "name": "Dijkot"},
    {"id": 48, "name": "Dinga"},
    {"id": 49, "name": "Dipalpur"},
    {"id": 50, "name": "Faisalabad"},
    {"id": 51, "name": "Fateh Jang"},
    {"id": 52, "name": "Gahkuch"},
    {"id": 53, "name": "Ghotki"},
    {"id": 54, "name": "Gilgit"},
    {"id": 55, "name": "Gochh"},
    {"id": 56, "name": "Gojra"},
    {"id": 57, "name": "Gujar Khan"},
    {"id": 58, "name": "Gujranwala"},
    {"id": 59, "name": "Gujrat"},
    {"id": 60, "name": "Gwadar"},
    {"id": 61, "name": "Hafizabad"},
    {"id": 62, "name": "Hangu"},
    {"id": 63, "name": "Haripur"},
    {"id": 64, "name": "Haroonabad"},
    {"id": 65, "name": "Hasan Abdal"},
    {"id": 66, "name": "Hasilpur"},
    {"id": 67, "name": "Hassan Abdal"},
    {"id": 68, "name": "Haveli Lakha"},
    {"id": 69, "name": "Hujra Shah Muqim"},
    {"id": 70, "name": "Hyderabad"},
    {"id": 71, "name": "Islamabad"},
    {"id": 72, "name": "Jacobabad"},
    {"id": 73, "name": "Jalalpur Bhattian"},
    {"id": 74, "name": "Jalalpur Jattan"},
    {"id": 75, "name": "Jampur"},
    {"id": 76, "name": "Jamshoro"},
    {"id": 77, "name": "Jaranwala"},
    {"id": 78, "name": "Jauharabad"},
    {"id": 79, "name": "Jhang"},
    {"id": 80, "name": "Jhelum"},
    {"id": 81, "name": "Kallar Syedan"},
    {"id": 82, "name": "Kamalia"},
    {"id": 83, "name": "Kandhkot"},
    {"id": 84, "name": "Kanganpur"},
    {"id": 85, "name": "Karachi"},
    {"id": 86, "name": "Karak"},
    {"id": 87, "name": "Karor Lal Esan"},
    {"id": 88, "name": "Kasur"},
    {"id": 89, "name": "Khairpur Tamiwali"},
    {"id": 90, "name": "Khanewal"},
    {"id": 91, "name": "Khanpur"},
    {"id": 92, "name": "Khanqah Sharif"},
    {"id": 93, "name": "Kharan"},
    {"id": 94, "name": "Kharian"},
    {"id": 95, "name": "Khushab"},
    {"id": 96, "name": "Khuzdar"},
    {"id": 97, "name": "Kohat"},
    {"id": 98, "name": "Kot Addu"},
    {"id": 99, "name": "Kot Radha Kishan"},
    {"id": 100, "name": "Kotli"},
    {"id": 101, "name": "Kulachi"},
    {"id": 102, "name": "Kumarwala"},
    {"id": 103, "name": "Lahore"},
    {"id": 104, "name": "Lakki Marwat"},
    {"id": 105, "name": "Lala Musa"},
    {"id": 106, "name": "Lalamusa"},
    {"id": 107, "name": "Lalian"},
    {"id": 108, "name": "Larkana"},
    {"id": 109, "name": "Layyah"},
    {"id": 110, "name": "Liaqauatpur"},
    {"id": 111, "name": "Lodhran"},
    {"id": 112, "name": "Mailsi"},
    {"id": 113, "name": "Malakwal"},
    {"id": 114, "name": "Malikwal"},
    {"id": 115, "name": "Mananwala"},
    {"id": 116, "name": "Mandi Bahauddin"},
    {"id": 117, "name": "Mansehra"},
    {"id": 118, "name": "Mardan"},
    {"id": 119, "name": "Marot"},
    {"id": 120, "name": "Matiari"},
    {"id": 121, "name": "Mian Channu"},
    {"id": 122, "name": "Mian Channun"},
    {"id": 123, "name": "Mianwali"},
    {"id": 124, "name": "Mianwali Bangla"},
    {"id": 125, "name": "Minchinabad"},
    {"id": 126, "name": "Mingora"},
    {"id": 127, "name": "Mirpur"},
    {"id": 128, "name": "Mirpur Khas"},
    {"id": 129, "name": "Mithankot"},
    {"id": 130, "name": "Multan"},
    {"id": 131, "name": "Muridke"},
    {"id": 132, "name": "Muzaffarabad"},
    {"id": 133, "name": "Muzaffargarh"},
    {"id": 134, "name": "Nankana Sahib"},
    {"id": 135, "name": "Narang Mandi"},
    {"id": 136, "name": "Narowal"},
    {"id": 137, "name": "Nartopa"},
    {"id": 138, "name": "Naushahro Firoz"},
    {"id": 139, "name": "Nawabshah"},
    {"id": 140, "name": "Noorpur"},
    {"id": 141, "name": "Nowshera"},
    {"id": 142, "name": "Okara"},
    {"id": 143, "name": "Pakpattan"},
    {"id": 144, "name": "Pasrur"},
    {"id": 145, "name": "Pattoki"},
    {"id": 146, "name": "Peshawar"},
    {"id": 147, "name": "Phool Nagar"},
    {"id": 148, "name": "Phularwan"},
    {"id": 149, "name": "Pind Dadan Khan"},
    {"id": 150, "name": "Pindi Bhattian"},
    {"id": 151, "name": "Pinjawana"},
    {"id": 152, "name": "Pir Mahal"},
    {"id": 153, "name": "Pishin"},
    {"id": 154, "name": "Qadirabad"},
    {"id": 155, "name": "Qaimpur"},
    {"id": 156, "name": "Qila Saifullah"},
    {"id": 157, "name": "Quetta"},
    {"id": 158, "name": "Rabwah"},
    {"id": 159, "name": "Rahim Yar Khan"},
    {"id": 160, "name": "Rajanpur"},
    {"id": 161, "name": "Rawalakot"},
    {"id": 162, "name": "Rawalpindi"},
    {"id": 163, "name": "Renala Khurd"},
    {"id": 164, "name": "Risalpur"},
    {"id": 165, "name": "Rojhan"},
    {"id": 166, "name": "Saddiqabad"},
    {"id": 167, "name": "Sadhoke"},
    {"id": 168, "name": "Sadiqabad"},
    {"id": 169, "name": "Safdarabad"},
    {"id": 170, "name": "Sahiwal"},
    {"id": 171, "name": "Saidu Sharif"},
    {"id": 172, "name": "Samundri"},
    {"id": 173, "name": "Sanghar"},
    {"id": 174, "name": "Sangla Hill"},
    {"id": 175, "name": "Sargodha"},
    {"id": 176, "name": "Sehwan Sharif"},
    {"id": 177, "name": "Shahpur"},
    {"id": 178, "name": "Shakargarh"},
    {"id": 179, "name": "Sheikhupura"},
    {"id": 180, "name": "Shekhupura"},
    {"id": 181, "name": "Shikarpur"},
    {"id": 182, "name": "Shorkot"},
    {"id": 183, "name": "Shujabad"},
    {"id": 184, "name": "Sialkot"},
    {"id": 185, "name": "Sibi"},
    {"id": 186, "name": "Skardu"},
    {"id": 187, "name": "Sukkur"},
    {"id": 188, "name": "Swabi"},
    {"id": 189, "name": "Tandlianwala"},
    {"id": 190, "name": "Tando Allahyar"},
    {"id": 191, "name": "Tando Muhammad Khan"},
    {"id": 192, "name": "Tank"},
    {"id": 193, "name": "Taunsa Sharif"},
    {"id": 194, "name": "Taxila"},
    {"id": 195, "name": "Timergara"},
    {"id": 196, "name": "Toba Tek Singh"},
    {"id": 197, "name": "Turbat"},
    {"id": 198, "name": "Umerkot"},
    {"id": 199, "name": "Usman Wala"},
    {"id": 200, "name": "Uthal"},
    {"id": 201, "name": "Vehari"},
    {"id": 202, "name": "Wah Cantonment"},
    {"id": 203, "name": "Wazirabad"},
    {"id": 204, "name": "Yazman"},
    {"id": 205, "name": "Zafarwal"},
    {"id": 206, "name": "Zahir Pir"},
    {"id": 207, "name": "Zhob"},
    {"id": 208, "name": "Ziarat"}
  ]

  export default cities