import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar2";
import AppCTA from "@/components/common/AppCTA";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ghost Protocols",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body  className={`${inter.className}`}>
      <Navbar/>
      {children}
      <AppCTA/>
      <Footer/>
      </body>
    </html>
  );
}
