import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/header/Navbar";
import AppCTA from "@/components/common/AppCTA";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ghost Protocols",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      <body  className={`dark ${inter.className}`}>
      <Navbar/>
      {children}
      <AppCTA/>
      </body>
    </html>
  );
}
